package ru.lc208.circulum.entities;// default package
// Generated 28 нояб. 2024 г., 21:40:16 by Hibernate Tools 6.2.8.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Competition generated by hbm2java
 */
@Entity
@Table(name="competition"
    ,schema="public"
)
public class Competition  implements java.io.Serializable {


     private int id;
     private String description;
     private String name;
     private Set<StudyProgram> studyPrograms = new HashSet<>(0);

    public Competition() {
    }

    public Competition(int id, String description, String name, Set<StudyProgram> studyPrograms) {
       this.id = id;
       this.description = description;
       this.name = name;
       this.studyPrograms = studyPrograms;
    }
   
     @Id 


    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="program_competition", schema="public", joinColumns = { 
        @JoinColumn(name="competition_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="program_id", nullable=false, updatable=false) })
    public Set<StudyProgram> getStudyPrograms() {
        return this.studyPrograms;
    }
    
    public void setStudyPrograms(Set<StudyProgram> studyPrograms) {
        this.studyPrograms = studyPrograms;
    }




}


