package ru.lc208.circulum.entities;// default package
// Generated 28 нояб. 2024 г., 21:40:16 by Hibernate Tools 6.2.8.Final


import jakarta.persistence.*;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.Filters;

import java.util.HashSet;
import java.util.Set;

/**
 * Competition generated by hbm2java
 */
@Entity
@Table(name="competition"
    ,schema="public"
)
public class Competition  implements java.io.Serializable {


    public boolean equals(Object obj) {
        if(obj instanceof Competition)
        {
            return this.id == ((Competition)obj).id;
        }
        return false;
    }


    private int id;
     private String description;
     private String name;
     private Set<StudyProgram> studyPrograms = new HashSet<>(0);
//    private int version;
//
//    @Version
//    @Column(name="version")
//    public int getVersion() {
//        return version;
//    }

//    public void setVersion(int version) {
//        this.version = version;
//    }
    public Competition() {
    }

    public Competition(int id, String description, String name, Set<StudyProgram> studyPrograms) {
       this.id = id;
       this.description = description;
       this.name = name;
       this.studyPrograms = studyPrograms;
    }
   
    @Id
    @Column(name="id", unique=true, nullable=false)
    @SequenceGenerator(name = "competition", sequenceName = "competition_id_seq", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "competition")
    public int getId() {
        return this.id;
    }


    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="program_competition", schema="public", joinColumns = {
        @JoinColumn(name="competition_id", nullable=false, updatable=false) }, inverseJoinColumns = {
        @JoinColumn(name="program_id", nullable=false, updatable=false) })
    public Set<StudyProgram> getStudyPrograms() {
        return this.studyPrograms;
    }
    
    public void setStudyPrograms(Set<StudyProgram> studyPrograms) {
        this.studyPrograms = studyPrograms;
    }

    @Override
    public String toString() {
        return name; // Показывать название департамента в ComboBox
    }


}


