package ru.lc208.circulum.entities;// default package
// Generated 28 нояб. 2024 г., 21:40:16 by Hibernate Tools 6.2.8.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="department"
    ,schema="public"
)
public class Department  implements java.io.Serializable {


     private int id;
     private Faculty faculty;
     private String depName;
     private int deanId;
     private Set teachers = new HashSet(0);
     private Set studyPlans = new HashSet(0);

    public Department() {
    }

    public Department(int id, Faculty faculty, String depName, int deanId, Set teachers, Set studyPlans) {
       this.id = id;
       this.faculty = faculty;
       this.depName = depName;
       this.deanId = deanId;
       this.teachers = teachers;
       this.studyPlans = studyPlans;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fac_id", nullable=false)
    public Faculty getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(Faculty faculty) {
        this.faculty = faculty;
    }

    
    @Column(name="dep_name", nullable=false)
    public String getDepName() {
        return this.depName;
    }
    
    public void setDepName(String depName) {
        this.depName = depName;
    }

    
    @Column(name="dean_id", nullable=false)
    public int getDeanId() {
        return this.deanId;
    }
    
    public void setDeanId(int deanId) {
        this.deanId = deanId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="department")
    public Set getTeachers() {
        return this.teachers;
    }
    
    public void setTeachers(Set teachers) {
        this.teachers = teachers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="department")
    public Set getStudyPlans() {
        return this.studyPlans;
    }
    
    public void setStudyPlans(Set studyPlans) {
        this.studyPlans = studyPlans;
    }




}


