package ru.lc208.circulum.entities;// default package
// Generated 28 нояб. 2024 г., 21:40:16 by Hibernate Tools 6.2.8.Final


import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name="department"
    ,schema="public"
)
public class Department  implements java.io.Serializable {

    public boolean equals(Object obj) {
        if(obj instanceof Department)
        {
            return this.id == ((Department)obj).id;
        }
        return false;
    }


     private int id;
     private Faculty faculty;
     private String depName;
     private int deanId;
     private Set<Teacher> teachers = new HashSet<>(0);
     private Set<StudyPlan> studyPlans = new HashSet<>(0);

    public Department() {
    }

    public Department(int id, Faculty faculty, String depName, int deanId, Set<Teacher> teachers, Set<StudyPlan>  studyPlans) {
       this.id = id;
       this.faculty = faculty;
       this.depName = depName;
       this.deanId = deanId;
       this.teachers = teachers;
       this.studyPlans = studyPlans;
    }
   
     @Id
    @Column(name="id", unique=true, nullable=false)
     @SequenceGenerator(name = "department", sequenceName = "department_id_seq", allocationSize = 1)
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "department")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fac_id", nullable=false)
    public Faculty getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(Faculty faculty) {
        this.faculty = faculty;
    }

    
    @Column(name="dep_name", nullable=false)
    public String getDepName() {
        return this.depName;
    }
    
    public void setDepName(String depName) {
        this.depName = depName;
    }

    
    @Column(name="dean_id", nullable=false)
    public int getDeanId() {
        return this.deanId;
    }
    
    public void setDeanId(int deanId) {
        this.deanId = deanId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="department")
    public Set<Teacher> getTeachers() {
        return this.teachers;
    }
    
    public void setTeachers(Set<Teacher> teachers) {
        this.teachers = teachers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="department")
    public Set<StudyPlan>  getStudyPlans() {
        return this.studyPlans;
    }
    
    public void setStudyPlans(Set<StudyPlan>  studyPlans) {
        this.studyPlans = studyPlans;
    }


    @Override
    public String toString() {
        return depName; // Показывать название департамента в ComboBox
    }

}


