package ru.lc208.circulum.entities;// default package
// Generated 28 нояб. 2024 г., 21:40:16 by Hibernate Tools 6.2.8.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Direction generated by hbm2java
 */
@Entity
@Table(name="direction"
    ,schema="public"
)
public class Direction  implements java.io.Serializable {


     private int id;
     private String dirName;
     private Set specialities = new HashSet(0);

    public Direction() {
    }

    public Direction(int id, String dirName, Set specialities) {
       this.id = id;
       this.dirName = dirName;
       this.specialities = specialities;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="dir_name", nullable=false)
    public String getDirName() {
        return this.dirName;
    }
    
    public void setDirName(String dirName) {
        this.dirName = dirName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="direction")
    public Set getSpecialities() {
        return this.specialities;
    }
    
    public void setSpecialities(Set specialities) {
        this.specialities = specialities;
    }




}


