package ru.lc208.circulum.entities;// default package
// Generated 28 нояб. 2024 г., 21:40:16 by Hibernate Tools 6.2.8.Final


import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * Faculty generated by hbm2java
 */
@Entity
@Table(name="faculty"
    ,schema="public"
)
public class Faculty  implements java.io.Serializable {

    public boolean equals(Object obj) {
        if(obj instanceof Faculty)
        {
            return this.id == ((Faculty)obj).id;
        }
        return false;
    }

     private int id;
     private String name;
     private Set<Department> departments = new HashSet<>(0);
     private Set<Speciality> specialities = new HashSet<>(0);

    public Faculty() {
    }

    public Faculty(int id, String name, Set<Department> departments, Set<Speciality> specialities) {
       this.id = id;
       this.name = name;
       this.departments = departments;
       this.specialities = specialities;
    }

    @Id
    @Column(name="id", unique=true, nullable=false)
    @SequenceGenerator(name = "faculty", sequenceName = "faculty_id_seq", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "faculty")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="faculty")
    public Set<Department> getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Set<Department> departments) {
        this.departments = departments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="faculty")
    public Set<Speciality> getSpecialities() {
        return this.specialities;
    }
    
    public void setSpecialities(Set<Speciality> specialities) {
        this.specialities = specialities;
    }


    @Override
    public String toString() {
        return name; // Показывать название департамента в ComboBox
    }

}


