package ru.lc208.circulum.entities;// default package
// Generated 28 нояб. 2024 г., 21:40:16 by Hibernate Tools 6.2.8.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * UserTeacherMapping generated by hbm2java
 */
@Entity
@Table(name="user_teacher_mapping"
    ,schema="public"
)
public class UserTeacherMapping  implements java.io.Serializable {


     private String userName;
     private int teacherId;

    public UserTeacherMapping() {
    }

    public UserTeacherMapping(String userName, int teacherId) {
       this.userName = userName;
       this.teacherId = teacherId;
    }
   
     @Id 

    
    @Column(name="user_name", unique=true, nullable=false)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="teacher_id", nullable=false)
    public int getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(int teacherId) {
        this.teacherId = teacherId;
    }




}


