package ru.lc208.circulum.entities;// default package
// Generated 28 нояб. 2024 г., 21:40:16 by Hibernate Tools 6.2.8.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * WorkType generated by hbm2java
 */
@Entity
@Table(name="work_type"
    ,schema="public"
)
public class WorkType  implements java.io.Serializable {


     private int id;
     private String workType;
     private int hours;
     private Set<StudyPlan> studyPlans = new HashSet<>(0);

    public WorkType() {
    }

    public WorkType(int id, String workType, int hours, Set<StudyPlan> studyPlans) {
       this.id = id;
       this.workType = workType;
       this.hours = hours;
       this.studyPlans = studyPlans;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="work_type", nullable=false)
    public String getWorkType() {
        return this.workType;
    }
    
    public void setWorkType(String workType) {
        this.workType = workType;
    }

    
    @Column(name="hours", nullable=false)
    public int getHours() {
        return this.hours;
    }
    
    public void setHours(int hours) {
        this.hours = hours;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="plan_wtype", schema="public", joinColumns = { 
        @JoinColumn(name="wtype_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="plan_id", nullable=false, updatable=false) })
    public Set<StudyPlan> getStudyPlans() {
        return this.studyPlans;
    }
    
    public void setStudyPlans(Set<StudyPlan> studyPlans) {
        this.studyPlans = studyPlans;
    }




}


